version: '3.7'

services:
  run_node:
    image: ghcr.io/cheqd/cheqd-node:${CHEQD_MAINNET_VERSION}
    user: cheqd
    ports: # target -> port inside container, published -> port on the host
      # REQUIRED: Tendermint peer-to-peer (P2P) port
      # Please do not change this unless you've also changed this in the external-address parameter in Tendermint config
      - target: 26656 
        published: ${TM_P2P_PORT}
        protocol: tcp
        mode: host
      # RECOMMENDED: Tendermint RPC port (required if you want to use chqed-noded CLI directly from the host)
      - target: 26657
        published: ${TM_JSON_RPC_PORT}
        protocol: tcp
        mode: host
      - target: 1317 
        published: ${TM_REST_API_PORT}
        protocol: tcp
        mode: host
      - target: 9090
        published: ${TM_GRPC_SERVER_PORT}
        protocol: tcp
        mode: host
      - target: 9091
        published: ${TM_GRPC_API_GATEWAY_PORT}
        protocol: tcp
        mode: host
      - target: 26660
        published: ${TM_PROMETHEUS_PORT}
        protocol: tcp
        mode: host
    env_file:
      - mainnet-container.env
    volumes:
      - type: volume
        source: cheqd_volume
        target: ${CHEQD_DOCKER_VOLUME_SOURCE}
    entrypoint: "node-runner"

volumes:
  cheqd_volume:
    driver: ${CHEQD_DOCKER_VOLUME_DRIVER}
    external: ${CHEQD_DOCKER_VOLUME_IS_EXTERNAL}
