version: '3.7'

services:
  run_node:
    image: ghcr.io/cheqd/cheqd-testnet:${CHEQD_TESTNET_VERSION}
    user: cheqd
    ports: # target -> port inside container, published -> port on the host
      - target: 26656 # P2P Service Port inside container (please don't change this unless you know what you're doing)
        published: ${TM_P2P_PORT}
        protocol: tcp
        mode: host
      - target: 26657
        published: ${TM_JSON_RPC_PORT}
        protocol: tcp
        mode: host
      - target: 1317
        published: ${TM_REST_API_PORT}
        protocol: tcp
        mode: host
      - target: 9090
        published: ${TM_GRPC_SERVER_PORT}
        protocol: tcp
        mode: host
      - target: 9091
        published: ${TM_GRPC_API_GATEWAY_PORT}
        protocol: tcp
        mode: host
      - target: 26660
        published: ${TM_PROMETHEUS_PORT}
        protocol: tcp
        mode: host
    env_file:
      - testnet-container.env
    volumes:
      - type: volume
        source: ${CHEQD_DOCKER_VOLUME_NAME}
        target: ${CHEQD_DOCKER_VOLUME_SOURCE}
    entrypoint: "node-runner"

volumes:
  ${CHEQD_DOCKER_VOLUME_NAME}:
    driver: ${CHEQD_DOCKER_VOLUME_DRIVER_TYPE}
    external: ${CHEQD_DOCKER_IS_EXTERNAL_VOLUME}
