name: "Build"

on: workflow_call

env:
  NODE_CONFIGS_BASE: "/home/runner/work/cheqd-node/cheqd-node/docker/localnet/network-config"

jobs:

  run-go-unit-tests:
    name: "Test: Golang unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Golang unit tests
        run: go test -v ./...

  build-binary:
    name: "Build: Node binary"
    needs: run-go-unit-tests
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Fetch Golang protoc compiler plugins
        env:
          GOLANG_PROTOBUF_VERSION: 1.3.5
          GOGO_PROTOBUF_VERSION: 1.3.2
          GRPC_GATEWAY_VERSION: 1.14.7
        # Taken from: tendermintdev/sdk-proto-gen:v0.2
        run: |
          go get \
            github.com/golang/protobuf/protoc-gen-go@v"$GOLANG_PROTOBUF_VERSION" \
            github.com/gogo/protobuf/protoc-gen-gogo@v"$GOGO_PROTOBUF_VERSION" \
            github.com/gogo/protobuf/protoc-gen-gogofast@v"$GOGO_PROTOBUF_VERSION" \
            github.com/gogo/protobuf/protoc-gen-gogofaster@v"$GOGO_PROTOBUF_VERSION" \
            github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v"$GRPC_GATEWAY_VERSION" \
            github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@v"$GRPC_GATEWAY_VERSION" \
            github.com/regen-network/cosmos-proto/protoc-gen-gocosmos@latest

      - name: Install buf
        env:
          PREFIX: "/usr/local"
          VERSION: "1.0.0-rc8"
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m).tar.gz" | \
          sudo tar -xvzf - -C "${PREFIX}" --strip-components 1

      - name: Build proto-gen
        run: |
          make proto-gen build

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-noded
          path: build/cheqd-noded

      - name: Set version number
        id: set-version
        run: |
          VERSION=$(build/cheqd-noded version 2>&1)
          echo "::set-output name=VERSION::$VERSION"

  build-packages:
    name: "Build: Debian and Tarball packages"
    runs-on: ubuntu-latest
    needs: build-binary
    env:
      VERSION: ${{ needs.build-binary.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Load binary artifact
        uses: actions/download-artifact@v3
        with:
          name: cheqd-noded

      - name: Restore binary permissions
        run: sudo chmod +x cheqd-noded

      - name: Build tarball
        working-directory: ./build-tools
        run: |
          ./build-tar.sh "../cheqd-noded"

      - name: Store tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-node_${{ env.VERSION }}.tar.gz
          path: build-tools/output/cheqd-node_${{ env.VERSION }}.tar.gz
      
      - name: Install fpm
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm

      - name: Build Debian package
        working-directory: ./build-tools
        run: |
          ./build-deb.sh "../cheqd-noded"

      - name: Store deb package artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-node_${{ env.VERSION }}_amd64.deb
          path: build-tools/output/cheqd-node_${{ env.VERSION }}_amd64.deb

  build-docker-images:
    name: "Build: Docker images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build cheqd-cli Docker image 'cheqd-noded' as entrypoint
        # TODO: Get rid of UID and GID
        run: docker build --target base -t cheqd-cli -f docker/Dockerfile --build-arg UID="$(id -u)" --build-arg GID="$(id -g)" .

      - name: Build cheqd-node Docker image with 'node-start' as entrypoint
        run: docker build --target node -t cheqd-node -f docker/Dockerfile --build-arg UID="$(id -u)" --build-arg GID="$(id -g)" .

      - name: Save cheqd-cli
        run: docker save -o cheqd-cli-image.tar cheqd-cli

      - name: Save cheqd-node
        run: docker save -o cheqd-node-image.tar cheqd-node

      - name: Store cheqd-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-cli-image.tar
          path: cheqd-cli-image.tar

      - name: Store cheqd-node artifact
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-node-image.tar
          path: cheqd-node-image.tar
