name: Build and Test

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Download and build starport
      run: curl https://get.starport.network/starport | bash

    - run: sudo mv starport /usr/local/bin/

    - name: Starport build
      run: starport build

  tests:
   name: Unit tests
   needs: build
   runs-on: ubuntu-latest
   steps:

   - name: Set up Go 1.x
     uses: actions/setup-go@v2
     with:
       go-version: ^1.13
     id: go

   - name: Check out code into the Go module directory
     uses: actions/checkout@v2

   - name: Run tests
     run: |
        go test -v ./x/verimcosmos/

