name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  call-build:
    name: "Build"
    needs: call-lint
    uses: ./.github/workflows/build.yml
  
  # call-test:
  #   name: "Test"
  #   needs: call-build
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     VERSION: ${{ needs.call-build.outputs.VERSION }}

  # check-for-release-tag:
  #   name: "Check for release tag"
  #   needs: call-build
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   run: 

  call-release:
    name: "Release"
    needs: call-build
    runs-on: ubuntu-latest
    
    steps:
      - name: "Check for release tag" 
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "Release tag found. Will trigger Release workflow"
      
      - name: "Trigger release workflow"
        if: ${{ success() }}
        uses: ./.github/workflows/release.yml
