name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  call-build:
    name: "Build"
    needs: call-lint
    uses: ./.github/workflows/build.yml
  
  # call-test:
  #   name: "Test"
  #   needs: call-build
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     VERSION: ${{ needs.call-build.outputs.VERSION }}

  call-release:
    name: "Release"
    needs: call-build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    with:
      RELEASE_VERSION: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
