name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  call-build:
    name: "Build"
    needs: call-lint
    uses: ./.github/workflows/build.yml
  
  # call-test:
  #   name: "Test"
  #   needs: call-build
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     VERSION: ${{ needs.call-build.outputs.VERSION }}

  check-for-release-tag:
    name: "Check for release tag"
    needs: call-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - run: echo "Release tag found. Will trigger Release workflow."

  call-release:
    name: "Release"
    needs: check-for-release-tag
    uses: ./.github/workflows/release.yml
