name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:

  workflow-setup:
    runs-on: ubuntu-latest
    outputs:
      CACHE_KEY_BUILD: ${{ steps.cache.outputs.CACHE_KEY_BUILD }}
      GITHUB_REPOSITORY_NAME: ${{ steps.cache.outputs.GITHUB_REPOSITORY_NAME }}
      VERSION: ${{ steps.cache.outputs.VERSION }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: cache
        run: |
          echo "::set-output name=CACHE_KEY_BUILD::${{ hashFiles('Dockerfile') }}"
          # Convert the GitHub repository name to lowercase
          echo "::set-output name=GITHUB_REPOSITORY_NAME::$(echo ${GITHUB_REPOSITORY,,})"
          echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"


  build-image:
    # Reference to workflow-setup job is required to access its various outputs.
    needs: workflow-setup
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      CACHE_KEY_BUILD: ${{ needs.workflow-setup.outputs.CACHE_KEY_BUILD }}

      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Try load from cache.
        id: cache-image
        uses: actions/cache@v2
        with:
          path: ${GITHUB_WORKSPACE}/cache
          key: ${{ env.CACHE_KEY_BUILD}}

      - name: If NOT found in cache, build and push image.
        if: steps.cache-image.outputs.cache-hit != 'true'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USER }} --password-stdin
          docker build -f .github/workflows/build/Dockerfile --no-cache -t ${{ env.GITHUB_REPOSITORY_NAME }}/node-build:${{ env.CACHE_KEY_BUILD }} .
          docker tag ${{ env.GITHUB_REPOSITORY_NAME }}/node-build:${{ env.CACHE_KEY_BUILD }} ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/node-build:${{ needs.workflow-setup.outputs.VERSION }}
          docker push ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/node-build:${{ needs.workflow-setup.outputs.VERSION }}
          mkdir -p ${GITHUB_WORKSPACE}/cache
          touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_BUILD }}

  tagged-release:
    name: "Tagged Release"
    needs: workflow-setup
    runs-on: "ubuntu-latest"

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Download and build starport
      run: curl https://get.starport.network/starport | bash

    - run: sudo mv starport /usr/local/bin/

    - name: Starport build
      run: starport build

    - name: Make archive
      run: |
        touch node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz
        tar -czf node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz --exclude=node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz .
    - name: Upload archive
      uses: actions/upload-artifact@v2
      with:
        name: node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz
        path: node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz

    - run: sudo apt-get install ruby ruby-dev rubygems build-essential
    - run: sudo gem install --no-document fpm

    - name: Creating deb package
      run: sh build_deb.sh -v ${{ needs.workflow-setup.outputs.VERSION }} -t node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz

    - name: Upload deb
      uses: actions/upload-artifact@v2
      with:
        name: node_${{ needs.workflow-setup.outputs.VERSION }}-1_amd64.deb
        path: node_${{ needs.workflow-setup.outputs.VERSION }}-1_amd64.deb


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          node_${{ needs.workflow-setup.outputs.VERSION }}.tar.gz
          node_${{ needs.workflow-setup.outputs.VERSION }}-1_amd64.deb


