name: "Release"
on:
  workflow_call:
    inputs:
      BUILD_VERSION:
        description: "Build version number"
        type: string
defaults:
  run:
    shell: bash

jobs:

  create-release:
    name: "Create release and publish"
    runs-on: ubuntu-latest
    outputs:
      VERSION: 
    env:
      REGISTRY: ghcr.io
    
    steps:
      - uses: actions/checkout@v3

      - name: Download tarball package
        uses: actions/download-artifact@v3
        with:
          name: cheqd-node_${{ inputs.VERSION }}.tar.gz

      - name: Download Debian package
        uses: actions/download-artifact@v3
        with:
          name: cheqd-node_${{ env.VERSION }}_amd64.deb



  publish-docker-image:
    name: "Publish images and release"
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download cheqd-cli image
        uses: actions/download-artifact@v2
        with:
          name: cheqd-cli-image.tar

      - name: Download cheqd-node image
        uses: actions/download-artifact@v2
        with:
          name: cheqd-node-image.tar

      - name: Load cheqd-cli image
        run: docker load -i cheqd-cli-image.tar

      - name: Load cheqd-node image
        run: docker load -i cheqd-node-image.tar

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push cheqd-node image
        run: |
          docker tag cheqd-node ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker tag cheqd-node ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Push cheqd-cli image
        run: |
          docker tag cheqd-cli ghcr.io/${{ github.repository_owner }}/cheqd-cli:${{ env.VERSION }}
          docker tag cheqd-cli ghcr.io/${{ github.repository_owner }}/cheqd-cli:latest
          docker push ghcr.io/${{ github.repository_owner }}/cheqd-cli:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/cheqd-cli:latest

      - name: Download deb
        uses: actions/download-artifact@v2
        with:
          name: cheqd-node_${{ env.VERSION }}_amd64.deb

      - name: Download tar
        uses: actions/download-artifact@v2
        with:
          name: cheqd-node_${{ env.VERSION }}.tar.gz
