name: "Release"
# on: workflow_call
on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: "Release version number"
        type: string
defaults:
  run:
    shell: bash


jobs:

  release-packages:
    name: "Release tar/Debian packages"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version

      - name: Download node binary from build stage
        uses: actions/download-artifact@v3
        with:
          name: cheqd-noded

      - name: Restore binary permissions
        run: sudo chmod +x cheqd-noded

      - name: Install fpm
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm

      - name: Build tarball package for release
        working-directory: ./build-tools
        run: |
          ./build-tar.sh "../cheqd-noded"

      - name: Store tarball artifact for release
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-node_${{ env.RELEASE_VERSION }}.tar.gz
          path: build-tools/output/cheqd-node_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Build Debian package for release
        working-directory: ./build-tools
        run: |
          ./build-deb.sh "../cheqd-noded"

      - name: Store Debian package artifact for release
        uses: actions/upload-artifact@v3
        with:
          name: cheqd-node_${{ env.RELEASE_VERSION }}_amd64.deb
          path: build-tools/output/cheqd-node_${{ env.RELEASE_VERSION }}_amd64.deb

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${GITHUB_REF_NAME}
          prerelease: true
          draft: true
          files: |
            build-tools/output/cheqd-node_${{ env.RELEASE_VERSION }}_amd64.deb
            build-tools/output/cheqd-node_${{ env.RELEASE_VERSION }}.tar.gz

  release-docker-images:
    name: "Publish Docker images for new version"
    runs-on: ubuntu-latest
    # needs: set-release-version
    env:
      REGISTRY: ghcr.io
      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version

      # - name: Set release version
      #   run: echo ::set-output name=RELEASE_VERSION::"${GITHUB_REF##*/}" >> "$GITHUB_ENV"

      - name: Download cheqd-cli Docker image
        uses: actions/download-artifact@v3
        with:
          name: cheqd-cli-image.tar

      - name: Download cheqd-node Docker image
        uses: actions/download-artifact@v3
        with:
          name: cheqd-node-image.tar

      - name: Load cheqd-cli image
        run: docker load -i cheqd-cli-image.tar

      - name: Load cheqd-node image
        run: docker load -i cheqd-node-image.tar

      - name: Login to Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push cheqd-node image
        run: |
          docker tag cheqd-node ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          docker tag cheqd-node ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Push cheqd-cli image
        run: |
          docker tag cheqd-cli ghcr.io/${{ github.repository_owner }}/cheqd-cli:${{ env.RELEASE_VERSION }}
          docker tag cheqd-cli ghcr.io/${{ github.repository_owner }}/cheqd-cli:latest
          docker push ghcr.io/${{ github.repository_owner }}/cheqd-cli:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/cheqd-cli:latest

      - name: Download deb
        uses: actions/download-artifact@v2
        with:
          name: cheqd-node_${{ env.RELEASE_VERSION }}_amd64.deb

      - name: Download tar
        uses: actions/download-artifact@v2
        with:
          name: cheqd-node_${{ env.RELEASE_VERSION }}.tar.gz
